print ("Vishal Gajage", "  ","Latur","  "," MCA ")
print ("Rupesh Jodh", "  ","Akola","  "," BE ")
print("Prasad Mule", "Solapur", "CSE")
print("Shubham Madavi", "Thane", "BE")
print("Mahesh Gavhane","Pune","BE")
print("Virendra Mali","Sangli","BE")
print("Supriya Awad","Pune","BE")
print("sourabh dhekale"," ", "kolhapur", " " "BE")
print("Sushant Damkondwar","Nanded","BE")
print("Nikita Khandare","Anjangaon Surji", "BE")
print("sushant chandanwar","Nanded", "BE")
